name: TypeScript OpenSSL Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-typescript:
    env:
      ImageOS: ubuntu24
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install OpenSSL
      run: sudo apt-get install -y openssl

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18'
        otp-version: '28'

    - name: Rebuild TypeScript
      run: make rebuild-ts

    - name: Run TypeScript OpenSSL Tests
      run: make test-ts

    - name: Start CA server
      run: |
        git clone https://github.com/synrc/ca.git 
        cd ca
        mix deps.get > /dev/null 2>&1
        mix compile > /dev/null 2>&1
        mix run --no-halt &
        CA_PID=$!
        
        # Ensure cleanup happens on exit (success or failure)
        trap "kill $CA_PID" EXIT
        
        sleep 5s
        cd ..
        make verify-ts
        cd Languages/TypeScript
        bun run main.ts
        